#!/bin/bash
if [ "$#" != 2 ]
then
    echo "usage : mmakefile [name] [-classic, -csfml or -ncurse]"
    echo -e "\nFile : (file that the makefile can create)\n
 - library\t: file with extension '.a' (ex: mmakefile libmy.a classic)
 - executable\t: binary file with extension '.out' or not (ex : mmakefile calc classic)
 \nFlag :
 - classic\t: for a classic Makefile
 - csfml\t: a Makefile with include of CSFML
 - ncurse\t: a Makefile with include of ncurse
 \nCommands:
 - clean\t: remove all unnecessary files
 - fclean\t: remove all unnecessary files and the binary
 - re\t: compile your code with your modifications
 - update\t: update your makefile with your new .c
 - prepush\t : remove all unnecessary files and the binary, add in your git and give you a status
 - full\t : update your makefile with your new .c and compile your code with your modifications
 - pull\t : maka a git pull
 - tree:\t : remove all unnecessary files and the binary, add in your git and give you a status and make a tree
 - debug:\t : remove all unnecessary files and the binary, add in your git and give you a status
 "
    exit
elif [ "$(find -maxdepth 2 -type f -name "*.c")" == "" ]
then
    echo -e "mmakefile : not '.c' files detected.
mmakefile : mmakefile must be executed in the folder containing your '.c' files."
    exit
fi

echo -e "##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## make file.
##

SRC\t=\t$(find -maxdepth 2 -type f -name "*.c" | sed ':a;N;$!ba;s/\n/ \\\n\t\t/g;$ s/$//g')\n
OBJ\t=\t\$(notdir \$(SRC:.c=.o))\n
NAME\t=\t$1\n"   >   Makefile

if [ "$1" == "$(echo $1 | grep -e "\w*\.a$")" ]
then
    echo -e "all:\t\$(NAME)\n
\$(NAME):
\tgcc -c \$(SRC)
\tar -rc \$(NAME) \$(OBJ)
\tcp \$(NAME) ..
\tmkdir -p ../../include
\tcp *.h ../../include\n
clean:
\trm -f *.o
\trm -f *# *~ ./*/*# ./*/*~ ./*/*/*# ./*/*/*~ vgcore*\n
fclean:\tclean
\trm -f \$(NAME)
\trm -r ../../include
\trm -f ../\$(NAME)\n
re:\tfclean all\n
valgrind:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC) -I include/ -L lib/ -lmy\n
update:
\tmmakefile $1 $2\n
prepush:\tfclean
\tgit add .\n\tgit status\n
push:\tprepush
\tgit commit -m \"push auto\"\n\tgit push origin master\n
full:\tupdate
\tmake re\n
pull:
\tgit pull origin master\n
tree:\tprepush
\ttree -a -I .git\n
debug:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC) -Wall -Wextra -pedantic -I include/ -L lib/ -lmy"   >>    Makefile
echo "Makefile avec la lib crée !"
elif [ "$(find -maxdepth 2 -type d -name "my")" == "./lib/my" ]
then
    echo -e "all:\t\$(NAME)\n
\$(NAME):
\tcd lib/my/ && make && cd ../..
\tgcc -c \$(SRC) -I include/ -L lib/ -lmy
\tgcc -o \$(NAME) \$(OBJ) -I include/ -L lib/ -lmy\n
clean:
\tcd lib/my/ && make clean && cd ../..
\trm -f *.o
\trm -f *# *~ ./*/*# ./*/*~ ./*/*/*# ./*/*/*~ vgcore*\n
fclean:\tclean
\trm -f \$(NAME)
\tcd lib/my/ && make fclean && cd ../..\n
re:\tfclean all\n
valgrind:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC) -I include/ -L lib/ -lmy\n
update:
\tmmakefile $1 $2\n
prepush:\tfclean
\tgit add .\n\tgit status"   >>   Makefile
echo "Makefile avec la lib crée !"
elif [ "$2" == "-csfml" ]
then
  echo -e "CSFML = -lcsfml-graphics -lcsfml-window -lcsfml-system -lcsfml-audio\n
all:\t\$(NAME)\n
\$(NAME):
\tgcc -c \$(SRC)
\tgcc -o \$(NAME) \$(OBJ) \$(CSFML)\n
clean:
\trm -f *.o
\trm -f *# *~ ./*/*# ./*/*~ ./*/*/*# ./*/*/*~ vgcore*\n
fclean:\tclean
\trm -f \$(NAME)\n
re:\tfclean all\n
valgrind:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC) \$(CSFML)
update:
\tmmakefile $1 $2\n
prepush: fclean
\tgit add .\n\tgit status\n
full:\tupdate
\tmake re\n
pull:
\tgit pull origin master\n
tree:\tprepush
\ttree -a -I .git\n
debug:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC) -Wall -Wextra -pedantic \$(CSFML)\n
push: prepush
\tgit commit -m \"push auto\"\n\tgit push origin master"   >>   Makefile
echo "Makefile csfml crée !"
elif [ "$2" == "-ncurse" ]
then
  echo -e "all:\t\$(NAME)\n
\$(NAME):
\tgcc -c \$(SRC)
\tgcc -o \$(NAME) \$(OBJ) -lncurses\n
clean:
\trm -f *.o
\trm -f *# *~ ./*/*# ./*/*~ ./*/*/*# ./*/*/*~ vgcore*\n
fclean:\tclean
\trm -f \$(NAME)\n
re:\tfclean all\n
valgrind:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC) -lncurses\n
update:
\tmmakefile $1 $2\n
prepush: fclean
\tgit add .\n\tgit status\n
full: update
\tmake re\n
pull:
\tgit pull origin master\n
tree: prepush
\ttree -a -I .git\n
debug: clean
\tgcc -g3 -o \$(NAME) \$(SRC) -Wall -Wextra -pedantic -lncurses\n
push: prepush
\tgit commit -m \"push auto\"\n\tgit push origin master"   >>   Makefile
echo "Makefile ncurse crée !"
else
    echo -e "all:\t\$(NAME)\n
\$(NAME):
\tgcc -c \$(SRC)
\tgcc -o \$(NAME) \$(OBJ)\n
clean:
\trm -f *.o
\trm -f *# *~ ./*/*# ./*/*~ ./*/*/*# ./*/*/*~ vgcore*\n
fclean:\tclean
\trm -f \$(NAME)\n
re:\tfclean all\n
valgrind:\tclean
\tgcc -g3 -o \$(NAME) \$(SRC)\n
update:
\tmmakefile $1 $2\n
prepush: fclean
\tgit add .\n\tgit status\n
full: update
\tmake re\n
pull:
\tgit pull origin master\n
tree: prepush
\ttree -a -I .git\n
debug: clean
\tgcc -g3 -o \$(NAME) \$(SRC) -Wall -Wextra -pedantic\n
push: prepush
\tgit commit -m \"push auto\"\n\tgit push origin master"   >>   Makefile
echo "Makefile classique crée !"
fi
